### PR TITLE
Linux Integration Example for Checking List of URLs and storing time and http response code

### PR DESCRIPTION
**Pull request by GaPeppy**
This linux integration uses a lookup file (urlcheck.json) and polls the URL for time and http response code.  The intent is to poll local services for a web-scale environment.  The example content of urlcheck.json is newrelic target domains.

### CODE REVIEW

**Comment by rubenruizdegauna** [comment]
Hi @GaPeppy Thanks for your contribution.

I just rebased from the GH UI but now I appear as the commiter and the commit is unverified :( Can you please rebase your branch and force push the commit?

I'll review it again and merge it.

Thanks

**Comment by GaPeppy** [comment]
I believe I've rebased - please review at your convenience.

**Comment by rubenruizdegauna** [comment]
> I believe I've rebased - please review at your convenience.

I guess the rebase didn't go as expected (I see 7 commits in this PR now) and I see that the master branch in the fork is not ok either :( 

Can you create a new brach from updated main, pick your commit and do another PR?

would you be able to recreate the fork and the PR? Thanks and sorry for the inconvenience.

**Comment by GaPeppy** [comment]
On it! - sorry for the hassle

**Pull request closed without merging**
