### PR TITLE
Added Oracle DB support.

### PR DESCRIPTION
**Pull request by miransar**
Adds support for OracleDB.

### CODE REVIEW

**Comment by Kav91** [comment]
Looks good but needs an example config put into the examples directory.

**Comment by miransar** [comment]
> Looks good but needs an example config put into the examples directory.

Done. Thanks.

**Review by Kav91 — APPROVED** [review]
LGTM nice work 👍🏾

**Comment by Kav91** [comment]
Given this works identical to our existing DB driver feature and is simply a drop-in, as well as still being classed as experimental. Will merge this to master as there are no direct support related impacts or potential impact to any existing supported features.

**Pull request merged**
