### PR TITLE
Plex Media Server Session Monitoring

### PR DESCRIPTION
**Pull request by icpenguins**
This is an example for using Flex to monitor Plex media server sessions.

### CODE REVIEW

**Review by thezackm — APPROVED** [review]
let's GTM

**Review by thezackm — CHANGES_REQUESTED** [review]
please change the file location; should be in the root of `/examples`, not in the `examples/flexConfigs` sub-directory

**Comment by icpenguins** [comment]
@thezackm sorry about that! Don't know how I did that in the first place.

**Review by thezackm — APPROVED** [review]
thanks @icpenguins!

**Pull request merged**
